# Trading Bot Configuration
trading:
  mode: paper
  symbols: ["AAPL", "TSLA", "MSFT"]
  timeframe: "1m"
  max_positions: 5

risk:
  max_position_size: 0.1
  max_daily_loss: 0.05
  stop_loss_pct: 0.02
  take_profit_pct: 0.04

models:
  random_forest:
    n_estimators: 100
    max_depth: 10
    prediction_threshold: 0.7
